---
version: '3.9'

services:
  frontend:
    image: web-project:dev
    container_name: web-template
    restart: always
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
    command: [ "dev" ]
